name: DosaDriver
description: "DosaDriver - Rider App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # ğŸ”¥ Firebase Core
  firebase_core: ^3.15.2

  # ğŸ” Authentication
  firebase_auth: ^5.7.0

  geolocator: ^10.1.0


  # ğŸ“¡ HTTP
  http: ^1.2.1
  shared_preferences: ^2.2.3

  # â˜ï¸ Firestore Database
  cloud_firestore: ^5.6.12

  # ğŸ—º Google Maps
  google_maps_flutter: ^2.9.0

  local_auth: ^2.1.8
  flutter_secure_storage: ^9.0.0

  # ğŸ“ Location Tracking
  location: ^5.0.0

  # ğŸ” Address Search & Geocoding
  google_places_flutter: ^2.0.8
  geocoding: ^2.1.1

  # ğŸ“¦ State Management (optional but recommended)
  provider: ^6.0.0

  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^20.0.0

  url_launcher: ^6.2.6

  # ğŸ¨ UI Enhancements
  flutter_typeahead: ^4.8.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/lang/en.json
    - assets/lang/ar.json

dependency_overrides:
  flutter_keyboard_visibility: 6.0.0
